[versions]

core = "1.19.0"
appcompat = "1.7.1"
material = "1.14.0"
constraintlayout = "2.2.1"

android = "9.2.1"

sdk-min = "23"
sdk-compile = "37"
sdk-target = "37"

[libraries]

core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]

android = { id = "com.android.application", version.ref = "android" }
library = { id = "com.android.library", version.ref = "android" }